spring:
  flyway:
    baseline-on-migrate: true
    enabled: true
  locations:
    - classpath:db/migration
  datasource:
    url: jdbc:postgresql://localhost:5432/template-test
    password: test
    username: test
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        generate_statistics: false
        order_inserts: true
        jdbc:
          batch_size: 100
        hbm2ddl:
          auto: validate